name = "ApproxOperator"
uuid = "6dcad7c1-d118-4fbd-9616-5407c5210a62"
authors = ["jcwu <jcwu@hqu.edu.cn> and contributors"]
version = "0.1.0"

[deps]
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
